[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

baseURL = 'https://laruffa.net/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "resume"
    weight = 2
    url = "resume"

      [[menu.header]]
    name = "projects"
    weight = 2
    url = "projects"

[params]
user = "mike"
hostname = "laruffa.net"
  [params.author]
    name = "Mike La Ruffa"  # Website and RSS feed author
    email = "mike@laruffa.net"  # RSS feed email address


readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/memzi513"
target = "_blank"
aria = "GitHub Profile"


[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/michael-laruffa-90aaa8330/"
aria = "LinkedIn Profile"

[[params.social]]
key = 3
name = "email"
url = "mailto:mike@laruffa.net"
aria = "My e-Mail Address"
