[module]
  [module.hugoVersion]
    min = "0.114.0"
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'
[params]
user = "hello"
hostname = "gohugo.io"

  [params.author]
    name = "Mr Hugo"
    avatar = "/avatar.png"
    avatarSize = "size-m"
    email = "hugo@example.com"
    avatarFirst = false
